spring:
# change the application name for your project name , this name is reserved for the maven archetype code generation
  application:
    name: SpringCloudConfigTesting
---
app:
    name: remote_external_app_new_changed value......
